feat: 38 add docker environment variable PACT_BROKER_WEBHOOK_HTTP_CODE_SUCCESS
pact-foundation/pact-broker-docker pull request #39
Opened 2021-02-18 12:16 UTC by pitschr

also masks the database password (otherwise it would be visible in e.g. AWS CloudWatch)

2021-02-18 22:02 UTC, bethesque requested changes

2021-02-18 22:02 UTC, bethesque commented on pact_broker/config.ru
> +dc.pact_broker_environment_variables.each { |key, value|
Good thinking. You'll find the code to do this is actually in `pact_broker/docker_configuration.rb`

```
def pact_broker_environment_variables
      pact_broker_environment_variable_names.sort.each_with_object({}) do | name, hash |
        hash[name] = name =~ /password/i ? "*****" : @env[name]
      end
    end
```

Would you mind updating that instead? Maybe just put it in a separate PR so I can merge the rest of it, which looks 👍🏽

2021-02-19 16:10 UTC, pitschr commented
Beth, it looks like the pact-broker-docker  is not checking the specs otherwise the issue which has been fixed here (line 222 and 227): https://github.com/pact-foundation/pact-broker-docker/pull/39/commits/590e284f1742c01dc575c745ee6eab69d83df42f would have been detected earlier. I just realized it because I added a test case for the PACT_BROKER_DATABASE_URL

2021-02-21 22:57 UTC, bethesque commented
Good point. We've recently moved from Travis to Github Actions, and while the tests do run in the "Update" workflow, I had forgotten to move the "test on push/pull request" over. I've just added that back now.

2021-02-21 23:04 UTC, merged

2021-02-22 02:43 UTC, bethesque commented
And it's out! I did a quick sanity check, but would love to get a 👍🏽 from you if you're using it in prod yourself.